name: CI

'on':
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements.txt
          pip install ruff mypy pytest
      - name: Lint (ruff)
        run: ruff check .
      - name: Format check (ruff-format)
        run: ruff format --check .
      - name: Type check (mypy)
        run: mypy .
      - name: Tests
        run: pytest -q

